//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsunDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_J_MessageData
    {
        public int ID { get; set; }
        public string SchoolID { get; set; }
        public string K_Number { get; set; }
        public string StudentName { get; set; }
        public string YW_RoomNum { get; set; }
        public string YW_SiteNum { get; set; }
        public string LS_RoomNum { get; set; }
        public string LS_SiteNum { get; set; }
        public string WS_RoomNum { get; set; }
        public string WS_SiteNum { get; set; }
        public string EN_RoomNum { get; set; }
        public string EN_SiteNum { get; set; }
        public string LZ_RoomNum { get; set; }
        public string LZ_SiteNum { get; set; }
        public string WZ_RoomNum { get; set; }
        public string WZ_SiteNum { get; set; }
        public string ZK_Number { get; set; }
        public string Remark { get; set; }
        public string StudentClass { get; set; }
        public string YW_Teacher { get; set; }
        public string LiShu_Teacher { get; set; }
        public string WS_Teacher { get; set; }
        public string EN_Teacher { get; set; }
        public string WL_Teacher { get; set; }
        public string HX_Teacher { get; set; }
        public string SW_Teacher { get; set; }
        public string ZZ_Teacher { get; set; }
        public string LiShi_Teacher { get; set; }
        public string DL_Teacher { get; set; }
        public string StudentID { get; set; }
    }
}
