//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsunDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_J_Teacher
    {
        public int ID { get; set; }
        public string SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string Subject { get; set; }
        public string TeacherName { get; set; }
        public string TeacherID { get; set; }
        public string TeacherSex { get; set; }
        public string TeacherTel { get; set; }
        public string PersonName { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remark { get; set; }
        public string IDNum { get; set; }
        public string BankNum { get; set; }
        public string BankName { get; set; }
    }
}
